const ImageTypes = {
  FETCH_IMAGE_START: "FETCH_IMAGE_START",
  IMAGE_IS_FETCHING: "IMAGE_IS_FETCHING",
  FETCH_IMAGE_SUCCESS: "FETCH_IMAGE_SUCCESS",
  FETCH_IMAGE_FAILURE: "FETCH_IMAGE_FAILURE",
};

export default ImageTypes;
